import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy | Colorado Springs Health Collective",
  description: "Privacy Policy for Colorado Springs Health Collective. Learn how we collect, use, and protect your personal information.",
};

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen">
      <div className="container mx-auto px-5 lg:px-8 pt-12 pb-16">
        <div className="max-w-3xl mx-auto">
          <div className="flex items-center justify-between mb-8">
            <h1 className="text-3xl lg:text-4xl font-bold" style={{ color: "hsl(0, 0%, 100%)" }}>Privacy Policy</h1>
            <a href="/privacy-policy.pdf" download className="flex items-center gap-2 px-4 py-2 rounded-full text-sm font-medium hover:opacity-80 transition-opacity" style={{ background: "hsla(210, 22%, 28%, 0.75)", color: "hsl(177, 70%, 65%)" }}>
              Download PDF
            </a>
          </div>
          <p className="text-sm mb-8" style={{ color: "hsl(210, 25%, 69%)" }}>Effective: 11/13/2025</p>

          <div style={{ color: "hsl(210, 40%, 89%)" }}>
            {[
              { heading: "1) Who We Are (Controller)", content: <><p className="mb-2">COBC Brands Direct Primary Care LLC d/b/a Colorado Springs Health Collective – Direct Primary Care ("Company," "we," "our," "us")</p><p>Covered domains: https://coshealthcollective.com and https://dpc.coshealthcollective.com</p></> },
              { heading: "2) Scope and Relationship to Our HIPAA Notice of Privacy Practices (NPP)", content: <p>This Privacy Policy explains how we collect, use, disclose, and protect personal information collected through our public websites, waitlist/interest forms, and non-clinical communications (the "Site"). Uses and disclosures of protected health information (PHI) in connection with patient care, the patient portal, and clinical communications through Hint are governed by our Notice of Privacy Practices (NPP), not this Privacy Policy. Please do not submit PHI through public web forms or email.</p> },
              { heading: "3) Patients Age 2+; Children's Privacy", content: <><p className="mb-2">Our membership and clinical services are available to patients age 2 and older.</p><p className="mb-2">The Site is intended for adults, but parents/guardians may use our public forms on behalf of minors. We do not knowingly collect personal information directly from children under 13 through the Site. If we learn that a child has provided information directly, we will delete it.</p><p>A parent/guardian who believes a child submitted information may contact us at dpc@coshealthcollective.com to request deletion.</p></> },
              { heading: "4) Personal Information We Collect (Website)", content: <><p className="mb-2">Depending on how you use the Site, we may collect:</p><ul className="list-disc pl-6 mb-4 space-y-1"><li>Identifiers and contact information (name, email, phone).</li><li>Commercial information (interest in membership or services).</li><li>Internet/technical information (device/browser type, pages viewed, referring/exit pages, timestamps, basic log data).</li><li>Inferences from the above (e.g., interest level in services).</li></ul><p className="mb-4">Sensitive data: We do not collect precise geolocation via the Site. Do not submit medical details through public forms.</p><h3 className="text-lg font-medium mb-2" style={{color:'hsl(0,0%,100%)'}}>Sources</h3><ul className="list-disc pl-6 space-y-1"><li>You (via waitlist and contact forms powered by SheetMonkey).</li><li>Automatic collection via cookies/analytics (Google Analytics).</li><li>Advertising platforms configured for measurement (Google Ads, Meta Ads).</li></ul></> },
              { heading: "5) How We Use Personal Information", content: <ul className="list-disc pl-6 space-y-1"><li>Provide, maintain, troubleshoot, and improve the Site.</li><li>Respond to inquiries and send non-clinical communications you request (e.g., waitlist updates).</li><li>Measure traffic and campaign performance in the aggregate (analytics and ad platform conversion reporting).</li><li>Detect and prevent fraud, security incidents, and misuse.</li><li>Comply with legal obligations and exercise legal rights.</li></ul> },
              { heading: "6) Cookies, Analytics, and Ad Platforms (No Targeted Advertising)", content: <p>We use Google Analytics to understand Site usage in the aggregate. We may also implement Google Ads and Meta pixel strictly for conversion measurement (e.g., how many people reached the waitlist page) and not for targeted advertising. We do not "sell" personal data or "share" personal data for targeted advertising. You can control cookies via your browser settings. We honor Global Privacy Control (GPC) signals where applicable.</p> },
              { heading: "7) How We Disclose Personal Information", content: <><p className="mb-2">We disclose personal information to:</p><ul className="list-disc pl-6 mb-4 space-y-1"><li>Service providers/Processors acting on our instructions and bound by contract (e.g., SiteGround for hosting, Google Workspace for business email, Replit for development/hosting services, SheetMonkey for forms).</li><li>Legal, safety, and compliance recipients when required (e.g., to comply with law, enforce terms, or protect our rights, security, and users).</li></ul><p className="mb-4">We do not sell personal information and do not share personal information for targeted advertising.</p><p>About PHI: Disclosures of PHI related to patient care are governed by our NPP (e.g., Hint as patient portal/billing). The Site's public forms are not for PHI.</p></> },
              { heading: "8) Your Privacy Rights (Colorado)", content: <><p className="mb-2">If you are a Colorado resident, you may exercise the following rights regarding personal data collected via the Site:</p><ul className="list-disc pl-6 mb-4 space-y-1"><li>Access: request confirmation and access to your personal data.</li><li>Correction: request that we correct inaccuracies.</li><li>Deletion: request deletion of personal data we collected from you.</li><li>Portability: request a copy of your data in a portable format.</li><li>Opt-Out: opt out of processing for targeted advertising, sale, or certain profiling (we do not conduct these activities).</li></ul><p className="mb-4">Timing: We will respond within 45 days (with a possible 45-day extension where permitted). We will verify your identity before fulfilling certain requests.</p><h3 className="text-lg font-medium mb-2" style={{color:'hsl(0,0%,100%)'}}>How to Submit a Request</h3><p className="mb-4">Email: dpc@coshealthcollective.com with the subject "Privacy Request" and tell us which right you wish to exercise. If submitting on someone else's behalf, include proof of authority.</p><h3 className="text-lg font-medium mb-2" style={{color:'hsl(0,0%,100%)'}}>Appeals</h3><p className="mb-4">If we deny your request, you may appeal by emailing dpc@coshealthcollective.com with the subject "Privacy Appeal." If you remain dissatisfied, you may contact the Colorado Attorney General.</p><h3 className="text-lg font-medium mb-2" style={{color:'hsl(0,0%,100%)'}}>Global Privacy Control (GPC)</h3><p>We honor browser-based GPC signals to the extent required.</p></> },
              { heading: "9) Data Retention (Website Data)", content: <><p className="mb-2">We retain website-related personal information only as long as reasonably necessary for the purposes described above or as required by law:</p><ul className="list-disc pl-6 mb-4 space-y-1"><li>Contact/waitlist form submissions (SheetMonkey): up to 24 months, then deletion or de-identification.</li><li>Server and security logs (hosting): ~90 days unless needed longer for security or investigations.</li><li>Marketing communications: until you unsubscribe or 24 months of inactivity.</li><li>Google Analytics data: generally up to 14 months (configure in GA admin).</li></ul><p>PHI retention is governed by our HIPAA policies and NPP (not this Policy).</p></> },
              { heading: "10) Security", content: <p>We maintain appropriate technical and organizational safeguards to protect Site-collected personal information against accidental, unlawful, or unauthorized access, use, loss, or disclosure. No system is perfectly secure, and we cannot guarantee absolute security. HIPAA safeguards for PHI are described in our internal policies and NPP.</p> },
              { heading: "11) Data Location (US Only)", content: <p>We store and process personal information in the United States and do not transfer it internationally.</p> },
              { heading: "12) Third-Party Links", content: <p>The Site may link to third-party websites and services we do not control. Their privacy practices are governed by their own policies.</p> },
              { heading: "13) Changes to This Privacy Policy", content: <p>We may update this Policy from time to time. If changes are material, we will provide a reasonable notice method (e.g., posting the updated Policy date at the top of this page and/or a site banner).</p> },
              { heading: "14) Contact Us (and Privacy Officer)", content: <><p className="mb-2">COBC Brands Direct Primary Care LLC d/b/a Colorado Springs Health Collective – Direct Primary Care</p><p className="mb-2">Attn: Privacy Officer (Logan Crist, PA-C)</p><p className="mb-2">1497 Solitaire St., Colorado Springs, CO 80905</p><p>Email: dpc@coshealthcollective.com</p></> },
              { heading: "15) Relationship to Other Terms", content: <p>This Policy applies to the Site. Your clinical relationship, PHI, and patient portal/billing via Hint are governed by our NPP and applicable patient/member agreements.</p> },
            ].map((section) => (
              <section key={section.heading} className="mb-8">
                <h2 className="text-xl font-semibold mb-4" style={{ color: "hsl(177, 70%, 65%)" }}>{section.heading}</h2>
                {section.content}
              </section>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
